PREFIX :      <http://www.swows.org/examples/circles#>
PREFIX tuio:  <http://www.swows.org/tuio#>
PREFIX vp:    <http://www.swows.org/viewport#> 
PREFIX swi:   <http://www.swows.org/instance#>

CONSTRUCT {
  ?circle :source ?tracked .
  ?circle :creationTime ?newCircleCreationTime .
  ?circle :centerX ?circleCenterX .
  ?circle :centerY ?circleCenterY .
}
WHERE {
  GRAPH :viewPortInfo {
    swi:GraphRoot
      vp:vpWidth ?vpWidth ;
      vp:vpHeight ?vpHeight .
  } .
  GRAPH :circles {
    ?circle :radius ?radius
  }
  ?circle :source ?tracked .
  ?circle :creationTime ?newCircleCreationTime .
  ?circle :centerX ?circleCenterX .
  ?circle :centerY ?circleCenterY .
  FILTER( ?radius * ?radius > ?vpWidth *?vpWidth + ?vpHeight * ?vpHeight ) .
}

